import { useEffect, useState, useRef } from 'react'
import { useParams, useNavigate, useLocation } from 'react-router-dom'
import { Download, Edit } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useProjectStore, useAppStore } from '@/stores'
import type { PRD } from '@/types'
import { ExportDialog } from './PRDDisplayExportDialog'
import { SaveDialog } from './PRDDisplaySaveDialog'
import { PRDDEditor } from './PRDDisplayEditor'
import { PRDDisplayStreamingView } from './PRDDisplayStreamingView'
import { FullDocTab } from './PRDDisplayTabs'
import { usePRDExport } from './usePRDExport'
import { usePRDSave } from './usePRDSave'
import { usePRDGeneration } from './usePRDGeneration'